/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Carrental_GroupG_37B;

import Dao.CarDao;
import controller.AddCarController;
import controller.controller;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mamta sah
 */
public class Addcar extends javax.swing.JFrame {
    /**
     * Creates new form Addcar
     */
    public Addcar() {
        
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();
        Browse = new javax.swing.JButton();
        imagepath = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        SeatingCap = new javax.swing.JTextField();
        acAvailability = new javax.swing.JComboBox<>();
        fuelType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Car:");

        brand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                brandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                brandFocusLost(evt);
            }
        });
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });

        model.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                modelFocusLost(evt);
            }
        });
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });

        type.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                typeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                typeFocusLost(evt);
            }
        });
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                priceFocusLost(evt);
            }
        });
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        Addbtn.setBackground(new java.awt.Color(255, 0, 0));
        Addbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Addbtn.setText("Add Car");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        Browse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Browse.setText("Browse");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        imagepath.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                imagepathFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                imagepathFocusLost(evt);
            }
        });
        imagepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagepathActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        SeatingCap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SeatingCapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SeatingCapFocusLost(evt);
            }
        });
        SeatingCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatingCapActionPerformed(evt);
            }
        });

        acAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non AC" }));

        fuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol ", "Diesel", "Electric" }));
        fuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancel)
                .addGap(30, 30, 30)
                .addComponent(Addbtn)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeatingCap, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagepath, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type)
                                .addComponent(model)))))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Browse)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(SeatingCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(acAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(fuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(imagepath, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Browse)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbtn)
                    .addComponent(cancel))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        String priceText = price.getText().trim();
        try {
            if (!priceText.isEmpty()) {
                Double.parseDouble(priceText);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be a valid number!");
            price.setText("");
        }
    
    }//GEN-LAST:event_priceActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
           
    }//GEN-LAST:event_AddbtnActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
      JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Car Image");
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagepath.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_BrowseActionPerformed

    private void imagepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagepathActionPerformed
      String path = imagepath.getText().trim();
        if (path.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select or enter a valid image path!");
        } else {
            JOptionPane.showMessageDialog(this, "Image path entered: " + path);
        }
    
    }//GEN-LAST:event_imagepathActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_cancelMouseClicked

    private void SeatingCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatingCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatingCapActionPerformed

    private void fuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTypeActionPerformed

    private void brandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandFocusGained
        if (brand.getText().equals("Brand")) {
            brand.setText("");
            brand.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_brandFocusGained

    private void brandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandFocusLost
        if (brand.getText().isEmpty()) {
            brand.setText("Brand");
            brand.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_brandFocusLost

    private void modelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelFocusGained
        if (model.getText().equals("Model")) {
            model.setText("");
            model.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_modelFocusGained

    private void modelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelFocusLost
        if (model.getText().isEmpty()) {
            model.setText("Model");
            model.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_modelFocusLost

    private void typeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typeFocusGained
        if (type.getText().equals("Type")) {
            type.setText("");
            type.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_typeFocusGained

    private void typeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typeFocusLost
        if (type.getText().isEmpty()) {
            type.setText("Type");
            type.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_typeFocusLost

    private void priceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusGained
          if (price.getText().equals("Price")) {
            price.setText("");
            price.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_priceFocusGained

    private void priceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusLost
           if (price.getText().isEmpty()) {
            price.setText("Price");
            price.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_priceFocusLost

    private void SeatingCapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SeatingCapFocusGained
        if (SeatingCap.getText().equals("Seating Capacity")) {
            SeatingCap.setText("");
            SeatingCap.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_SeatingCapFocusGained

    private void SeatingCapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SeatingCapFocusLost
        if (SeatingCap.getText().isEmpty()) {
            SeatingCap.setText("Seating Capacity");
            SeatingCap.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_SeatingCapFocusLost

    private void imagepathFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imagepathFocusGained
        if (imagepath.getText().equals("Image Path")) {
            imagepath.setText("");
            imagepath.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_imagepathFocusGained

    private void imagepathFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imagepathFocusLost
        if (imagepath.getText().isEmpty()) {
            imagepath.setText("Image Path");
            imagepath.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_imagepathFocusLost

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Browse;
    public javax.swing.JTextField SeatingCap;
    public javax.swing.JComboBox<String> acAvailability;
    public javax.swing.JTextField brand;
    private javax.swing.JButton cancel;
    public javax.swing.JComboBox<String> fuelType;
    public javax.swing.JTextField imagepath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField model;
    public javax.swing.JTextField price;
    public javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables


   public void addBrowseListener(ActionListener listener) {
    Browse.addActionListener(listener);
}

public String getBrand() {
    return brand.getText();
}

public String getImagePath() {
    return imagepath.getText();
}

public String getModel() {
    return model.getText();
}

public String getPrice() {
    return price.getText();
}

public String getCarType() {
    return type.getText();
}

public int getSeatingCap() {
    try {
        return Integer.parseInt(SeatingCap.getText()); // Assuming JTextField for seating
    } catch (NumberFormatException e) {
        return 0; // Default value if invalid
    }
}

public String getAcAvailability() {
    return (String) acAvailability.getSelectedItem(); // Assuming JComboBox
}

public String getFuelType() {
    return (String) fuelType.getSelectedItem(); // Assuming JComboBox
}

public void addAddBtnListener(ActionListener listener) {
    Addbtn.addActionListener(listener);
}
}