/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Carrental_GroupG_37B;

import controller.BookCarController;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author mamta sah
 */
public class BookCar extends javax.swing.JFrame {
public javax.swing.JComboBox<String> carSelection; // Add this in Form Editor
    /**
     * Creates new form BookCar
     */
    public BookCar() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DateFirst = new com.toedter.calendar.JDateChooser();
        DateSecond = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        Pickup = new javax.swing.JTextField();
        Drop = new javax.swing.JTextField();
        ConfirmBooking = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DateFirst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFirstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DateFirstFocusLost(evt);
            }
        });

        DateSecond.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateSecondFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DateSecondFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Car");

        Pickup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PickupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PickupFocusLost(evt);
            }
        });
        Pickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickupActionPerformed(evt);
            }
        });

        Drop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DropFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DropFocusLost(evt);
            }
        });
        Drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropActionPerformed(evt);
            }
        });

        ConfirmBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmBooking.setForeground(new java.awt.Color(255, 51, 51));
        ConfirmBooking.setText("Confirm Booking");

        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 51, 51));
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DateFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(DateSecond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Drop, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ConfirmBooking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancel)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(DateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(DateSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Drop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmBooking)
                    .addComponent(Cancel))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickupActionPerformed

    private void DropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropActionPerformed

    private void DateFirstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFirstFocusGained
        if (DateFirst.getDate() == null) {
            DateFirst.setDate(null);
            DateFirst.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_DateFirstFocusGained

    private void DateFirstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFirstFocusLost
        if (DateFirst.getDate() == null) {
            DateFirst.setDate(new java.util.Date());
            DateFirst.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_DateFirstFocusLost

    private void DateSecondFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateSecondFocusGained
        if (DateSecond.getDate() == null) {
            DateSecond.setDate(null);
            DateSecond.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_DateSecondFocusGained

    private void DateSecondFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateSecondFocusLost
        if (DateSecond.getDate() == null) {
            DateSecond.setDate(new java.util.Date());
            DateSecond.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_DateSecondFocusLost

    private void PickupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PickupFocusGained
        if (Pickup.getText().trim().equals("Pickup Location")) {
            Pickup.setText("");
            Pickup.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_PickupFocusGained

    private void PickupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PickupFocusLost
         if (Pickup.getText().trim().isEmpty()) {
            Pickup.setText("Pickup Location");
            Pickup.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_PickupFocusLost

    private void DropFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DropFocusGained
        if (Drop.getText().trim().equals("Enter Drop Location")) {
            Drop.setText("");
            Drop.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_DropFocusGained

    private void DropFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DropFocusLost
        if (Drop.getText().trim().isEmpty()) {
            Drop.setText("Enter Drop Location");
            Drop.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_DropFocusLost

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
         this.setVisible(false);
    }//GEN-LAST:event_CancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Cancel;
    public javax.swing.JButton ConfirmBooking;
    public com.toedter.calendar.JDateChooser DateFirst;
    public com.toedter.calendar.JDateChooser DateSecond;
    public javax.swing.JTextField Drop;
    public javax.swing.JTextField Pickup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


    public Date getDateFirst() {
        return DateFirst.getDate();
    }

    public Date getDateSecond() {
        return DateSecond.getDate();
    }

    public String getPickup() {
        return Pickup.getText();
    }

    public String getDrop() {
        return Drop.getText();
    }

    // Added listener methods
    public void addConfirmBookingListener(ActionListener listener) {
        ConfirmBooking.addActionListener(listener);
    }

    public void addCancelListener(ActionListener listener) {
        Cancel.addActionListener(listener);
    }
}

