/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Carrental_GroupG_37B;

import javax.swing.JPanel;

/**
 *
 * @author mamta sah
 */
public class BookingHistory extends javax.swing.JPanel {

    /**
     * Creates new form BookingHistory
     */
    public BookingHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void clearBookings() {
        NCar.setText("");
        type.setText("");
        modelC.setText("");
        price.setText("");
        carImage.setIcon(null);
        // Clear any other components if needed
    }

    public void addBookingPanel(JPanel panel) {
       
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NCar = new javax.swing.JLabel();
        modelC = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        carImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 153));
        setPreferredSize(new java.awt.Dimension(535, 140));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(535, 140));

        NCar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NCar.setText("Toyota");

        modelC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modelC.setText("SUV");

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText("Price");

        type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        type.setText("Toyota Fortuner GR-S");

        carImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carrental_GroupG_37B/WhatsApp Image 2025-05-29 at 21.24.13_8b689230.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(carImage, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(type, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(NCar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carImage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NCar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(type)
                        .addGap(10, 10, 10)
                        .addComponent(modelC)
                        .addGap(10, 10, 10)
                        .addComponent(price)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel NCar;
    public javax.swing.JLabel carImage;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel modelC;
    public javax.swing.JLabel price;
    public javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables

}
