/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;
import java.awt.event.ActionListener;

/**
 *
 * @author Menuka
 */
public class BookaCar extends javax.swing.JFrame {

    /**
     * Creates new form BookaCar
     */
    public BookaCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Namefield = new javax.swing.JTextField();
        PhoneNumberfield = new javax.swing.JTextField();
        Emailfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
       
        Bookbutton = new javax.swing.JButton();
        Cancelbutton = new javax.swing.JButton();
        Selectpickuplocationfield = new javax.swing.JTextField();
        Selectdroplocationfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));


        Namefield.setText("Name");
        Namefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NamefieldFocusLost(evt);
            }
        });

        PhoneNumberfield.setText("Phone Number");
        PhoneNumberfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneNumberfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneNumberfieldFocusLost(evt);
            }
        });
        PhoneNumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberfieldActionPerformed(evt);
            }
        });

        Emailfield.setText("Email");
        Emailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailfieldFocusLost(evt);
            }
        });
        Emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailfieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel1.setText("Book A Car");

        

        Bookbutton.setBackground(new java.awt.Color(255, 0, 51));
        Bookbutton.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        Bookbutton.setText("Confirm Booking");
        Bookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookbuttonActionPerformed(evt);
            }
        });

        Cancelbutton.setBackground(new java.awt.Color(255, 0, 51));
        Cancelbutton.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        Cancelbutton.setText("Cancel");

        Selectpickuplocationfield.setText("Select Pickup Location");

        Selectdroplocationfield.setText("Select Drop Location");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Bookbutton)
                        .addGap(33, 33, 33)
                        .addComponent(Cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                  
                                    .addComponent(Namefield)
                                    .addComponent(Emailfield)
                                    .addComponent(PhoneNumberfield, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                   
                                    .addComponent(Selectpickuplocationfield)
                                    .addComponent(Selectdroplocationfield))
                                .addGap(37, 37, 37)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhoneNumberfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selectpickuplocationfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selectdroplocationfield, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bookbutton)
                    .addComponent(Cancelbutton))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneNumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberfieldActionPerformed

    private void EmailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailfieldActionPerformed

    private void BookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookbuttonActionPerformed

    private void NamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamefieldFocusGained
        // TODO add your handling code here:
         if(Namefield.getText().equals("Name")){
           Namefield.setText("");
    }
        
    }//GEN-LAST:event_NamefieldFocusGained

    private void NamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamefieldFocusLost
        // TODO add your handling code here:
        if(Namefield.getText().isEmpty()){
            Namefield.setText("Name");
            
        }
        
    }//GEN-LAST:event_NamefieldFocusLost

    private void EmailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailfieldFocusGained
        // TODO add your handling code here:
        if(Emailfield.getText().equals("Email")){
           Emailfield.setText("");
    }
        
    }//GEN-LAST:event_EmailfieldFocusGained

    private void EmailfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailfieldFocusLost
        // TODO add your handling code here:
         if(Emailfield.getText().isEmpty()){
           Emailfield.setText("Email");
            
        }
        
    }//GEN-LAST:event_EmailfieldFocusLost

    private void PhoneNumberfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberfieldFocusGained
        // TODO add your handling code here:
        if(PhoneNumberfield.getText().equals("PhoneNumber")){
           PhoneNumberfield.setText("");
    }
        
    }//GEN-LAST:event_PhoneNumberfieldFocusGained

    private void PhoneNumberfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNumberfieldFocusLost
        // TODO add your handling code here:
         if(PhoneNumberfield.getText().isEmpty()){
          PhoneNumberfield.setText("PhoneNumber");
            
        }
        
    }//GEN-LAST:event_PhoneNumberfieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BookaCar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookbutton;
    private javax.swing.JButton Cancelbutton;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JTextField Namefield;
    private javax.swing.JTextField PhoneNumberfield;
    private javax.swing.JTextField Selectdroplocationfield;
    private javax.swing.JTextField Selectpickuplocationfield;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    
    public void addBookCarListener(ActionListener listener) {
        Bookbutton.addActionListener(listener);
    }

    public String getCustomerName() {
        return Namefield.getText();
    }

    public String getCustomerEmail() {
        return Emailfield.getText();
    }

    public String getPhoneNumber() {
        return PhoneNumberfield.getText();
    }

    public String getPickupLocation() {
        return Selectpickuplocationfield.getText();
    }

    public String getDropLocation() {
        return Selectdroplocationfield.getText();
    }

    public String getDate() {
        
        return jDateChooser1.getDate().toString();
    }

    public String getDate2() {
        return jDateChooser2.getDate().toString(); 
    }
}
    

