/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Menuka
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enteryourfullname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enteryourusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enteryourpassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enterconfirmpassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        enteryouremail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Full Name:");

        enteryourfullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enteryourfullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enteryourfullnameFocusLost(evt);
            }
        });
        enteryourfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteryourfullnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("User Name:");

        enteryourusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enteryourusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enteryourusernameFocusLost(evt);
            }
        });
        enteryourusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteryourusernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Password:");

        enteryourpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enteryourpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enteryourpasswordFocusLost(evt);
            }
        });
        enteryourpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteryourpasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Confirm Password:");

        enterconfirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterconfirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterconfirmpasswordFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Email:");

        enteryouremail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enteryouremailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enteryouremailFocusLost(evt);
            }
        });
        enteryouremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteryouremailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Car Rental Nepal");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Register");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Already have an account?Login here.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enteryouremail, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteryourpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enteryourusername, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(enteryourfullname))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteryourfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteryourusername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteryourpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteryouremail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enteryourfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteryourfullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteryourfullnameActionPerformed

    private void enteryourpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteryourpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteryourpasswordActionPerformed

    private void enteryourusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteryourusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteryourusernameActionPerformed

    private void enteryouremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteryouremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteryouremailActionPerformed

    private void enteryourfullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryourfullnameFocusGained
        // TODO add your handling code here:
        if(enteryourfullname.getText().equals("enter your name")){
            enteryourfullname.setText("");
    }//GEN-LAST:event_enteryourfullnameFocusGained

    private void enteryourfullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryourfullnameFocusLost
        // TODO add your handling code here:
        if(enteryourfullname.getText().isEmpty()){
            enteryourfullname.setText(" enter your name");
    }//GEN-LAST:event_enteryourfullnameFocusLost

    private void enteryourusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryourusernameFocusGained
        // TODO add your handling code here:
        if(enteryourusername.getText().isEmpty()){
            enteryourusername.setText(" enter your username");
    }                                           
        
    }//GEN-LAST:event_enteryourusernameFocusGained

    private void enteryourusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryourusernameFocusLost
        // TODO add your handling code here:
        if(enteryourusername.getText().isEmpty()){
            enteryourusername.setText(" enter your username");
    }                                           
        
    }//GEN-LAST:event_enteryourusernameFocusLost

    private void enteryourpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryourpasswordFocusGained
        // TODO add your handling code here:
        if(enteryourpassword.getText().isEmpty()){
            enteryourpassword.setText("password");
        
    }//GEN-LAST:event_enteryourpasswordFocusGained

    private void enteryourpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryourpasswordFocusLost
        // TODO add your handling code here:
        if(enteryourpassword.getText().isEmpty()){
            enteryourpassword.setText("password");
        
    }//GEN-LAST:event_enteryourpasswordFocusLost

    private void enterconfirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterconfirmpasswordFocusGained
        // TODO add your handling code here:
         if(enterconfirmpassword.getText().isEmpty()){
            enterconfirmpassword.setText("confirmpassword");
        
        
    }//GEN-LAST:event_enterconfirmpasswordFocusGained

    private void enterconfirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterconfirmpasswordFocusLost
        // TODO add your handling code here:
        if(enterconfirmpassword.getText().isEmpty()){
            enterconfirmpassword.setText("confirmpassword");
        
        
    }//GEN-LAST:event_enterconfirmpasswordFocusLost

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    private void enteryouremailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryouremailFocusGained
        // TODO add your handling code here:
        if(enteryouremail.getText().isEmpty()){
            enteryouremail.setText("email");
    }//GEN-LAST:event_enteryouremailFocusGained

    private void enteryouremailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enteryouremailFocusLost
        // TODO add your handling code here:
        if(enteryouremail.getText().isEmpty()){
            enteryouremail.setText("email");
        
    }//GEN-LAST:event_enteryouremailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterconfirmpassword;
    private javax.swing.JTextField enteryouremail;
    private javax.swing.JTextField enteryourfullname;
    private javax.swing.JTextField enteryourpassword;
    private javax.swing.JTextField enteryourusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
